name: sql_charter_server
author: Herbert Poul
version: 0.0.1
description: SQL Chart Server
dependencies:
  intl: any
  logging: any
  polymer: any
  postgresql: any
  route: any
transformers:
- polymer:
    entry_points: 
      - web/index.html