name: timeline_charter
author: Herbert Poul
version: 0.0.1
description: Simple way to chart time based values based on SQL Queries.
dependencies:
  intl: any
  logging: any
  polymer: any
  postgresql: any
  route: any
transformers:
- polymer:
    entry_points:
    - web/index.html
