name: timeline_charter
author: Herbert Poul <herbert.poul@gmail.com>
version: 0.0.1
homepage: https://github.com/hpoul/timeline_charter
description: Simple way to chart time based values based on SQL Queries.
dependencies:
  intl: '>=0.9.1 <0.10.0'
  logging: '>=0.9.1+1 <0.10.0'
  polymer: '>=0.9.4 <0.10.0'
  postgresql: '>=0.2.13 <0.3.0'
  route: '>=0.4.6 <0.5.0'
transformers:
- polymer:
    entry_points: []
